# Generated by Django 5.0.6 on 2024-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carMng", "0004_car_drivetrain_car_engine_car_mileage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="drivetrain",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="car",
            name="mileage",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(max_length=200),
        ),
    ]
